name: TWRP CI

on:
  workflow_dispatch:

jobs:
  build:
    name: TWRP Build CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    env:
      OEM: samsung
      DEVICE: lt02

    steps:
    - uses: actions/checkout@v2

    - name: Installing build dependencies
      run: |
        sudo apt-get install zip gcc-multilib g++-multilib \
          libc6-dev-i386 lib32ncurses5-dev lib32z1-dev \
          libgl1-mesa-dev libxml2-utils xsltproc schedtool

    - name: Syncing TWRP sources
      run: |
        mkdir ~/TWRP
        cd ~/TWRP

        mkdir ~/.bin
        curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
        python3 ~/.bin/repo init -b twrp-6.0 --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git
        git clone --single-branch --branch twrp-5.1 https://github.com/T21x-TWRP/twrp_device_samsung_lt02.git ~/TWRP/device/samsung/lt02
        python3 ~/.bin/repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)

    - name: Building TWRP
      run: |
        cd ~/TWRP
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        export LC_ALL=C
        lunch omni_${{env.DEVICE}}-eng
        make -j$(nproc --all) recoveryimage

    - name: Uploading TWRP builds
      uses: actions/upload-artifact@v2
      with:
        name: twrp
        path: /home/runner/TWRP/out/target/product/${{env.DEVICE}}/recovery.*
